### ISSUE TITLE
PIxel 4a 5g

### ISSUE THREAD

**Issue by niloydas97** [V3rB0se/Alynx-nethunter-sunfish#1]
can I use this kernel on my pixel 4a 5g, without any bug?

**Comment by V3rB0se** [comment]
Pixel 4a 5G isn't supported but you can contribute to pixel 4a 5G development. I don't own this device so I can't test the stability of my builds. Join me on telegram and we'll build a kernel for pixel 4a 5g (bramble) together :) https://t.me/alynx_sepiol/

**Comment by V3rB0se** [comment]
there's a build on xda now you can test it :)
