### ISSUE TITLE
Which toolchain to use?

### ISSUE THREAD

**Issue by yesimxev** [V3rB0se/Alynx-nethunter-sunfish#2]
Hi, I've tried to build with clang-10, and 12 but no success, says fstack-protector-strong is not supported

**Comment by V3rB0se** [comment]
hi, sorry i was busy with the project, you should use clang 14 [clang-r445002](https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/836b6c7f87c4c946d860ef664052282939a9bd31/clang-r445002/)

**Comment by yesimxev** [comment]
Thanks! Can you try to build and merge if it works for you? https://github.com/V3rB0se/Alynx-nethunter-sunfish/pull/3

Would be awesome and resolve https://gitlab.com/kalilinux/nethunter/apps/kali-nethunter-app/-/issues/331

**Comment by V3rB0se** [comment]
Hi, The source is not up to date i forgot to update it. I'll try to update the sources first can you ask him to flash the [latest build](https://forum.xda-developers.com/t/kernel-nethunter-for-pixel-4a-sunfish-android-12-android-13.4464651/post-87108855) that is available on XDA?

**Comment by V3rB0se** [comment]
The default branch is now `alynx_android-13.0.0_r0.17` can you create a new pull request with the updated source. in the meantime I'll compile the kernel and create a new pull request in devices repo and update the thread on xda

**Comment by yesimxev** [comment]
Awesome! Now seems you added the latest nethunter_defconfig, so it has all the necessary Bluetooth drivers.
